server:
  port: ${PORT}

ead:
  service-registry:
    username: ${EUREKA_USERNAME_PROD}
    password: ${EUREKA_PASSWORD_PROD}
    authority: ${EUREKA_AUTHORITY_PROD}

spring:
  #Datasource
  datasource:
    url: "jdbc:postgresql://localhost:5432/ead-service-registry?currentSchema=sc_service_registry&autoreconnect=true"
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non-contextual-creation: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    register-with-eureka: false #This line prevents eureka to auto register
    fetch-registry: false #It won't fetch its own registration in eureka
    service-url:
      default-zone: ${EUREKA_URL}
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80