server:
  port: 8761

ead:
  service-registry:
    username: serviceregistry
    password: 'ead123sr'
    authority: 'ROLE_ADMIN'

spring:
  #Datasource
  datasource:
    url: "jdbc:postgresql://localhost:5432/ead-service-registry?currentSchema=sc_service_registry&autoreconnect=true"
    username: edersonjseder
    password: Postgres1756
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non-contextual-creation: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#This config won't be in production
eureka:
  client:
    register-with-eureka: false #This line prevents eureka to auto register
    fetch-registry: false #It won't fetch its own registration in eureka
    service-url:
      default-zone: 'http://${ead.service-registry.username}:${ead.service-registry.password}@localhost:8761/eureka'